baseURL = "/"
relativeurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
title = "pokyah"
theme = "minimal"
disqusShortname = "pokyah-github-io"
googleAnalytics = ""

[params]
    author = "Thomas Goossens"
    description = "Geographer/Data-analyst/Geostatistician @ CRA-W"
    githubUsername = "pokyah"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "dracula"
    highlightLanguages = ["go", "R", "bash", "javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About me"
    weight = 3
    
[[menu.main]]
    url = "/meta/"
    name = "Meta"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:hello.pokyah@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/pokyah/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/thomasgoossens1985/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/pokyah/"
    name = "stack-overflow"
    weight = 5
    
[[menu.icon]]
  url = "https://open.spotify.com/user/pokyah?si=YzQxOB8yR-KLO4VdWhETjg"
  name = "spotify"
  weight = 6  
