---
title: Favorite repositories
author: Thomas Goossens
date: '2017-04-01'
---

# My favorite repos'

## books

* [Geocomputation with R](http://geocompr.robinlovelace.net/)  
Publicly available and with an excellent chapter about spatial cross-validation.

* [Efficient R Programming](https://csgillespie.github.io/efficientR/)
Worth reading to improve your R skills and workflows for a better productivity

* [Happy git with R](http://happygitwithr.com/big-picture.html)
Work efficiently with R + git combo

## Data-analasis packages

* [mlr with R](https://mlr-org.github.io/mlr/)  
"umbrella" package for machine learning (Machine learning, more specifically the field of predictive modeling is primarily concerned with minimizing the error of a model or making the most accurate predictions possible, at the expense of explainability)

* [mlr benchmark vis](https://github.com/collinleiber/benchmarkVis)
Benchmark Visualizations in R


## Purely Agromet

* [Public Agromet code](https://github.com/pokyah/agrometeor-public)  
Working tested code related to the Agromet project and sufficiently documented.

* [AgrometeoR Docker](https://github.com/pokyah/agrometeorDocker)  
Dockerfile for AgrometeoR development environment using Docker

* [AgrometeoR Spatial Benchmarking](https://github.com/pokyah/agrometeor-spatial-benchmarking)
Benchmark of various machine learning regression methods

* [AWS Humain Comparison](https://github.com/pokyah/AWS-Humain-comparison)
Comparing measurements from 2 types of automatic weather stations

* [Spatialization Review and Benchmarking](https://pokyah.github.io/agrometeor-spatialization-review-benchmark/)

* [Spatialization methodology](https://pokyah.github.io/agrometeor-methodo-spatial/)
Presentation about Agromet Spatialization methodo

## My work

* [my personal blog](https://pokyah.github.io)  
Where I post my tutorials related to openGIS, data-analysis and Linux stuffs

* [R utilities](https://pokyah.github.io/R-utilities/)
Global R utility functions

* [R project initializer](https://github.com/pokyah/R-project-init)
Create a tree and .gitignore for your new R project with a single command

* [CRA-W revealjs template](https://github.com/pokyah/craw-reveal-template)  
CSS template for authoring revealjs presentations with the CRA-W graphic chart.


## Other blogs  

* [Robert Miles](https://robertmyles.github.io/post/)

* [Fred Vanwin Blog](https://frdvnw.github.io)
R + Linux tips & tricks	

* [Dean Attali](https://deanattali.com/)
R shiny consultant. Lots of tips & tricks

* [Sean Anderson](https://github.com/seananderson/seananderson.github.com)
R biologist + blogger

* [strimas](http://strimas.com/r/snowfall/)
R & open geosciences

* [r-spatial](https://r-spatial.github.io)
sf packages & spatial R stuffs

* [stat545](https://github.com/STAT545-UBC/STAT545-UBC.github.io)
Qualitative R-courses 